// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission6try2.Models;

namespace mission6try2.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230213155340_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("mission6try2.Models.MovieInput", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Family",
                            Director = "David Mickey Evans",
                            Edited = false,
                            LentTo = "",
                            Notes = "Great Movie",
                            Rating = "PG",
                            Title = "The Sandlot",
                            Year = 1993
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Comedy",
                            Director = "Jon Turteltaub",
                            Edited = false,
                            LentTo = "",
                            Notes = "Good Movie",
                            Rating = "PG",
                            Title = "Cool Runnings",
                            Year = 1993
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Drama",
                            Director = "Brian Helgeland",
                            Edited = false,
                            LentTo = "",
                            Notes = "Super Movie",
                            Rating = "PG-13",
                            Title = "42",
                            Year = 2013
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
